query searchEvents($input: PaginatedInputEventsSearchInput!) {
  searchEvents(input: $input) {
    data {
      id
      name
      galleries {
        id
        description
        images {
          id
          hosting
          url
        }
      }
    }
  }
}
